services:
  web-deploy:
    build: .
    command: python3 main.py
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.deploy.rule=Host(`deploy.sna.lol`)"
      - "traefik.http.routers.deploy.entrypoints=websecure"
      - "traefik.http.routers.deploy.tls.certresolver=myresolver"
      - "traefik.http.routers.deploy.priority=10"
    networks:
      - traefik_network
    expose:
      - "80"
    volumes:
      - /nomerhub_front:/app/nomerhub_front
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  traefik_network:
    external: true